<?php
// =============================================
// lang.php - Textes fixes multilingues
// =============================================

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

if (empty($_SESSION['langue'])) {
    $_SESSION['langue'] = 'en';
}

function langueCourante()
{
    return ($_SESSION['langue'] ?? 'en') === 'fr' ? 'fr' : 'en';
}

function t($key)
{
    $langue = langueCourante();

    $textes = [
        'en' => [
            'home' => 'Home',
            'dashboard' => 'My space',
            'trends' => 'Trends',
            'search' => 'Search',
            'settings' => 'Settings',
            'login' => 'Log in',
            'logout' => 'Log out',
            'register' => 'Sign up',
            'add' => 'Add',
            'add_webtoon' => 'Add a webtoon',
            'my_list' => 'My list',
            'details' => 'View details',
            'details_unavailable' => 'Details unavailable',
            'already_added' => 'Already added',
            'edit_progress' => 'Edit my progress',
            'delete' => 'Delete',
            'save' => 'Save',
            'cancel' => 'Cancel',
            'status' => 'Status',
            'chapters' => 'Chapters',
            'chapter_current' => 'Current chapter',
            'score' => 'Score',
            'personal_score' => 'Personal score',
            'comment' => 'Personal comment',
            'intention' => 'Intention',
            'continue' => 'I plan to continue',
            'unsure' => 'I am not sure yet',
            'stop' => 'I do not plan to continue',
            'to_read' => 'To read',
            'reading' => 'Reading',
            'paused' => 'Paused',
            'finished' => 'Finished',
            'dropped' => 'Dropped',
            'filters' => 'Filters',
            'genre' => 'Genre',
            'all_genres' => 'All genres',
            'sort_by' => 'Sort by',
            'popularity' => 'Popularity',
            'recent' => 'Recent',
            'apply' => 'Apply',
            'title' => 'Title',
            'author' => 'Author',
            'description' => 'Description',
            'summary' => 'Summary',
            'information' => 'Information',
            'average_score' => 'Average score',
            'mean_score' => 'Mean score',
            'favourites' => 'Favourites',
            'country' => 'Country',
            'start_date' => 'Start date',
            'end_date' => 'End date',
            'genres' => 'Genres',
            'characters' => 'Characters',
            'staff' => 'Staff',
            'related' => 'Related works',
            'see_anilist' => 'View on AniList',
            'language' => 'Language',
            'english' => 'English',
            'french' => 'French',
            'adult_content' => 'Adult content',
            'save_settings' => 'Save settings',
            'settings_saved' => 'Settings saved.',
            'search_placeholder' => 'Search for a webtoon, author or genre...',
            'search_start' => 'Search for a webtoon, manhwa or manga to begin.',
            'no_result' => 'No AniList result for this search.',
            'welcome' => 'Welcome to Webtoon-Library',
            'welcome_text' => 'Track your reading, rate your favorite webtoons and organize your personal library.',
            'create_account' => 'Create an account',
            'password' => 'Password',
            'email' => 'Email address',
            'pseudo' => 'Username',
            'required_fields' => 'Please fill in all fields.',
            'bad_login' => 'Incorrect username or password.',
            'manual_add_warning' => 'Manual additions may not have AniList details.',
            'anilist_no_match' => 'AniList could not find a reliable match for this title.',
            'all' => 'All',
            'total_webtoons' => 'Total webtoons',
            'currently_reading' => 'Currently reading',
            'recently_added' => 'Recently added',
            'view_all' => 'View all',
            'first_webtoon' => 'Add my first webtoon',
            'unknown_author' => 'Unknown author',
            'not_rated' => 'Not rated yet',
            'not_filled' => 'Not filled in',
            'back' => 'Back',
            'my_progress' => 'My personal progress',
            'volumes' => 'Volumes',
            'manual_add' => 'Manual add',
            'image_url' => 'Image URL',
            'required_title' => 'Title is required.',
            'score_error' => 'The score must be between 0 and 10.',
            'add_success' => 'Webtoon added successfully.',
            'edit_success' => 'Webtoon updated successfully.',
            'delete_success' => 'Webtoon deleted.',
            'already_in_library' => 'This webtoon is already in your library.',
            'add_error' => 'Unable to add this webtoon.',
            'added_to_library' => 'Webtoon added to your library.',
            'trending_intro' => 'Explore current trends, future gems and popular classics from AniList.',
            'future_gem' => 'Future gem',
            'old_gem' => 'Old gem',
            'top_adult' => 'Top +18',
            'general' => 'General',
            'results' => 'results',
            'no_section_result' => 'No result for this section.',
            'more_trends' => 'View more trends',
            'more_future' => 'View more future gems',
            'more_old' => 'View more old gems',
            'more_adult' => 'View more +18'
        ],
        'fr' => [
            'home' => 'Accueil',
            'dashboard' => 'Mon espace',
            'trends' => 'Tendance',
            'search' => 'Rechercher',
            'settings' => 'Paramètres',
            'login' => 'Connexion',
            'logout' => 'Déconnexion',
            'register' => "S'inscrire",
            'add' => 'Ajouter',
            'add_webtoon' => 'Ajouter un webtoon',
            'my_list' => 'Ma liste',
            'details' => 'Voir détails',
            'details_unavailable' => 'Détails indisponibles',
            'already_added' => 'Déjà ajouté',
            'edit_progress' => 'Modifier mon suivi',
            'delete' => 'Supprimer',
            'save' => 'Enregistrer',
            'cancel' => 'Annuler',
            'status' => 'Statut',
            'chapters' => 'Chapitres',
            'chapter_current' => 'Chapitre actuel',
            'score' => 'Note',
            'personal_score' => 'Note personnelle',
            'comment' => 'Commentaire personnel',
            'intention' => 'Intention',
            'continue' => 'Je compte continuer',
            'unsure' => 'Je ne sais pas encore',
            'stop' => 'Je ne compte pas continuer',
            'to_read' => 'À lire',
            'reading' => 'En cours',
            'paused' => 'En pause',
            'finished' => 'Terminé',
            'dropped' => 'Abandonné',
            'filters' => 'Filtres',
            'genre' => 'Genre',
            'all_genres' => 'Tous les genres',
            'sort_by' => 'Trier par',
            'popularity' => 'Popularité',
            'recent' => 'Récent',
            'apply' => 'Appliquer',
            'title' => 'Titre',
            'author' => 'Auteur',
            'description' => 'Description',
            'summary' => 'Résumé',
            'information' => 'Informations',
            'average_score' => 'Note moyenne',
            'mean_score' => 'Score moyen',
            'favourites' => 'Favoris',
            'country' => 'Pays',
            'start_date' => 'Début',
            'end_date' => 'Fin',
            'genres' => 'Genres',
            'characters' => 'Personnages',
            'staff' => 'Staff',
            'related' => 'Œuvres liées',
            'see_anilist' => 'Voir sur AniList',
            'language' => 'Language / Langue',
            'english' => 'English',
            'french' => 'Français',
            'adult_content' => 'Contenus +18',
            'save_settings' => 'Enregistrer',
            'settings_saved' => 'Préférences enregistrées.',
            'search_placeholder' => 'Rechercher un webtoon, un auteur ou un genre...',
            'search_start' => 'Recherchez un webtoon, un manhwa ou un manga pour commencer.',
            'no_result' => 'Aucun résultat AniList pour cette recherche.',
            'welcome' => 'Bienvenue sur Webtoon-Library',
            'welcome_text' => 'Suivez vos lectures, notez vos webtoons préférés et organisez votre bibliothèque personnelle.',
            'create_account' => 'Créer un compte',
            'password' => 'Mot de passe',
            'email' => 'Adresse email',
            'pseudo' => 'Pseudo',
            'required_fields' => 'Veuillez remplir tous les champs.',
            'bad_login' => 'Pseudo ou mot de passe incorrect.',
            'manual_add_warning' => 'Les ajouts manuels peuvent ne pas avoir de détails AniList.',
            'anilist_no_match' => "AniList n'a pas trouvé de correspondance fiable pour ce titre.",
            'all' => 'Tous',
            'total_webtoons' => 'Webtoons au total',
            'currently_reading' => 'En cours de lecture',
            'recently_added' => 'Ajoutés récemment',
            'view_all' => 'Voir tout',
            'first_webtoon' => 'Ajouter mon premier webtoon',
            'unknown_author' => 'Auteur inconnu',
            'not_rated' => 'Pas encore notée',
            'not_filled' => 'Non renseigné',
            'back' => 'Retour',
            'my_progress' => 'Mon suivi personnel',
            'volumes' => 'Volumes',
            'manual_add' => 'Ajout manuel',
            'image_url' => "URL de l'image",
            'required_title' => 'Le titre est obligatoire.',
            'score_error' => 'La note doit être comprise entre 0 et 10.',
            'add_success' => 'Webtoon ajouté avec succès.',
            'edit_success' => 'Webtoon modifié avec succès.',
            'delete_success' => 'Webtoon supprimé.',
            'already_in_library' => 'Ce webtoon est déjà dans votre bibliothèque.',
            'add_error' => "Impossible d'ajouter ce webtoon.",
            'added_to_library' => 'Webtoon ajouté à votre bibliothèque.',
            'trending_intro' => 'Explore les tendances, les futures pépites et les classiques populaires depuis AniList.',
            'future_gem' => 'Future pépite',
            'old_gem' => 'Ancienne pépite',
            'top_adult' => 'Top +18',
            'general' => 'Général',
            'results' => 'résultats',
            'no_section_result' => 'Aucun résultat pour cette section.',
            'more_trends' => 'Voir plus de tendances',
            'more_future' => 'Voir plus de futures pépites',
            'more_old' => "Voir plus d'anciennes pépites",
            'more_adult' => 'Voir plus de +18'
        ]
    ];

    return $textes[$langue][$key] ?? $textes['en'][$key] ?? $key;
}
?>
